In [ ]:
# INS


# 1 GB
# /data/INS/02_02_2024_10_16_27_bag_0.db3


# 89 GB
# /data/INS/11_01_2023_17_15_56_bag_0.db3



In [ ]:


%load_ext autoreload
%autoreload 2

import os
import sys
# sys.path.append(os.environ['HOME'] + "/repos/dataengine/")

from dataengine.source import DataSources
from dataengine.buffer import DataBuffer

from rosbags.highlevel import AnyReader
from rosbags.serde import deserialize_cdr

import numpy as np
from pathlib import Path




The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [20]:


## ROS2 INS data
file_path = os.environ['HOME'] + "/repos/monorepo/external_files/data/INS/small/02_02_2024_10_16_27_bag_0.db3"
source = DataSources(file_path)



In [21]:

axis = "/novatel/oem7/odom"

buffer_depth = 1000
buffer = DataBuffer(source, buffer_depth, axis=axis)

print(buffer.get_topics())

for buf, count in buffer.get_data():
    if count > 100:
        break



['/novatel/oem7/bestutm', '/novatel/oem7/odom', '/novatel/oem7/bestpos', '/events/write_split', '/novatel/oem7/odom_origin', '/novatel/oem7/bestvel', '/disk_usage', '/client_count', '/blackfly_5/meta', '/anello/odom', '/novatel/oem7/time', '/blackfly_5/camera_info_ext', '/blackfly_4/camera_info', '/connected_clients', '/novatel/oem7/mark2time', '/blackfly_5/camera_info', '/flight_number', '/novatel/oem7/insstdev', '/blackfly_4/meta', '/blackfly_4/camera_info_ext', '/novatel/oem7/inspva', '/novatel/oem7/imu/data', '/blackfly_3/meta', '/novatel/oem7/gps', '/novatel/oem7/terrastarinfo', '/novatel/oem7/oem7raw', '/anello/imu', '/novatel/oem7/insconfig', '/novatel/oem7/terrastarstatus', '/parameter_events', '/novatel/oem7/fix', '/novatel/oem7/imu/data_raw', '/novatel/oem7/ppppos', '/novatel/oem7/inspvax', '/pilot_notes', '/blackfly_2/meta', '/rosout', '/novatel/oem7/corrimu', '/blackfly_2/camera_info', '/backend_response', '/blackfly_1/meta', '/blackfly_2/camera_info_ext', '/blackfly_1/came

In [22]:

axis = "/novatel/oem7/odom"

buffer.roll_buffer(axis)

data = buffer[-1]

print("shape: ", data.shape)

print("pose: ", data[0])

data = buffer[:]

print("poses: ", data[:, 0, :10])

print("x values average: ", np.average(data[:, 0, 0]))


####


axis = "/anello/imu"

buffer.roll_buffer(axis)

data = buffer[-1]

print("shape: ", data.shape)

print("orientation: ", data[0])

data = buffer[:]

print("orientations: ", data[:, 0, :10])

print("x values average: ", np.average(data[:, 0, 0]))




shape:  (8, 4)
pose:  [3.95119453e+05 3.87982418e+06 8.36170385e+02 0.00000000e+00]
poses:  [[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 ...
 [3.95119453e+05 3.87982418e+06 8.36170385e+02 0.00000000e+00]
 [3.95119453e+05 3.87982418e+06 8.36170385e+02 0.00000000e+00]
 [3.95119453e+05 3.87982418e+06 8.36170385e+02 0.00000000e+00]]
x values average:  40302.18373418326
shape:  (6, 4)
orientation:  [0. 0. 0. 1.]
orientations:  [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
x values average:  0.0


In [23]:

axis = "/novatel/oem7/fix"


buffer.roll_buffer(axis)

data = buffer[-1]

print("shape: ", data.shape)

data = buffer[:]

print("lat: ", data[0])
print("lng: ", data[1])
print("alt: ", data[2])


shape:  (3,)
lat:  [0. 0. 0.]
lng:  [0. 0. 0.]
alt:  [0. 0. 0.]


In [ ]:

### Using the database

axis = "/novatel/oem7/odom"

buffer_depth = 1000
buffer = DataBuffer(source, buffer_depth, axis=axis, use_db=True)

print(buffer.get_topics())

buffer.load_data_db(axis)


['/novatel/oem7/bestutm', '/novatel/oem7/odom', '/novatel/oem7/bestpos', '/events/write_split', '/novatel/oem7/odom_origin', '/novatel/oem7/bestvel', '/disk_usage', '/client_count', '/blackfly_5/meta', '/anello/odom', '/novatel/oem7/time', '/blackfly_5/camera_info_ext', '/blackfly_4/camera_info', '/connected_clients', '/novatel/oem7/mark2time', '/blackfly_5/camera_info', '/flight_number', '/novatel/oem7/insstdev', '/blackfly_4/meta', '/blackfly_4/camera_info_ext', '/novatel/oem7/inspva', '/novatel/oem7/imu/data', '/blackfly_3/meta', '/novatel/oem7/gps', '/novatel/oem7/terrastarinfo', '/novatel/oem7/oem7raw', '/anello/imu', '/novatel/oem7/insconfig', '/novatel/oem7/terrastarstatus', '/parameter_events', '/novatel/oem7/fix', '/novatel/oem7/imu/data_raw', '/novatel/oem7/ppppos', '/novatel/oem7/inspvax', '/pilot_notes', '/blackfly_2/meta', '/rosout', '/novatel/oem7/corrimu', '/blackfly_2/camera_info', '/backend_response', '/blackfly_1/meta', '/blackfly_2/camera_info_ext', '/blackfly_1/came

In [ ]:


### All data is now in database!!!

print(buffer[:].shape)

print("x values average: ", np.average(data[:, 0, 0]))



In [ ]:

axis = "/novatel/oem7/odom"
buffer.set_axis(axis)
data = buffer[:]
print("pose x values average: ", np.average(data[:, 0, 0]))


In [ ]:

axis = "/anello/imu"
buffer.set_axis(axis)
data = buffer[:]
print("orientation x values average: ", np.average(data[:, 0, 0]))
